CREATE TABLE IF NOT EXISTS OrgUsers (
    UserID INTEGER,
    OrgID INTEGER,
    PermissionLevel INTEGER DEFAULT 0,
    FOREIGN KEY (UserID) REFERENCES Users(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (OrgID) REFERENCES Orgs(ID) ON DELETE CASCADE ON UPDATE CASCADE
)